import type { Config } from "tailwindcss";

export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#ffb1c5",
        "outline-variant": "#bec8cb",
        error: "#ba1a1a",
        surface: "#fff7fa",
        "on-tertiary-container": "#693c4d",
        "surface-dim": "#dfd8db",
        outline: "#6f797b",
        "on-tertiary-fixed-variant": "#65394b",
        "primary-container": "#77c5d5",
        "on-secondary-fixed-variant": "#8f0045",
        "inverse-primary": "#84d2e2",
        "surface-bright": "#fff7fa",
        "tertiary-fixed-dim": "#f2b6cb",
        "on-surface-variant": "#3f484b",
        "surface-variant": "#e8e0e3",
        "primary-fixed-dim": "#84d2e2",
        "inverse-on-surface": "#f7eff2",
        "surface-container-low": "#f9f2f5",
        "on-primary": "#ffffff",
        "on-secondary-fixed": "#3f001a",
        secondary: "#b41b5c",
        "on-tertiary-fixed": "#330f1f",
        "surface-container-highest": "#e8e0e3",
        "on-secondary-container": "#62002d",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "inverse-surface": "#332f32",
        "on-error": "#ffffff",
        "on-primary-container": "#00525d",
        "on-background": "#1e1b1d",
        "surface-container-high": "#eee6e9",
        "error-container": "#ffdad6",
        primary: "#006876",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#e4a9be",
        background: "#fff7fa",
        "surface-container": "#f4ecef",
        "surface-tint": "#006876",
        "on-surface": "#1e1b1d",
        "secondary-fixed": "#ffd9e1",
        "on-primary-fixed": "#001f25",
        tertiary: "#805062",
        "primary-fixed": "#a1efff",
        "tertiary-fixed": "#ffd9e4",
        "on-primary-fixed-variant": "#004e5a",
      },
      borderRadius: {
        DEFAULT: "1rem",
        lg: "2rem",
        xl: "3rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["Newsreader", "serif"],
        body: ["Plus Jakarta Sans", "sans-serif"],
        label: ["Plus Jakarta Sans", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
